[deps]
AtlasRobot = "436ed74b-f7b6-57fe-bd82-efdbd6c0ab0c"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
